services:
    
  node_app:
    image: node:lts-alpine
    container_name: base-node
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: sh -c "while true; do sleep 60; done"


