version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
